# Generated by Django 5.0.1 on 2024-02-01 03:58

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2024, 2, 1, 0, 58, 45, 944563), editable=False, verbose_name='DATE ADDED')),
                ('date', models.DateField(default=datetime.datetime.now, help_text='Date of the entry', verbose_name='DATE')),
                ('time', models.IntegerField(default=10, help_text='Time in minutes', verbose_name='TIME')),
                ('description', models.TextField(help_text='What did you do?', verbose_name='DESCRIPTION')),
            ],
        ),
    ]
