# Generated by Django 5.0.1 on 2024-02-03 00:16

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='DATE ADDED')),
                ('name', models.CharField(help_text='Name of the type', max_length=100, verbose_name='NAME')),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='DATE ADDED')),
                ('date', models.DateField(default=datetime.datetime.now, help_text='Date of the entry', verbose_name='DATE')),
                ('time', models.DurationField(default=10, help_text='Time in minutes', verbose_name='TIME')),
                ('description', models.TextField(help_text='What did you do?', verbose_name='DESCRIPTION')),
                ('type', models.ForeignKey(help_text='What type of work did you do?', on_delete=django.db.models.deletion.PROTECT, to='timesheet.type', verbose_name='TYPE')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
                'ordering': ['-date'],
            },
        ),
    ]
