# Generated by Django 5.0.1 on 2024-02-01 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetentry',
            name='type',
            field=models.ForeignKey(help_text='What type of work did you do?', on_delete=django.db.models.deletion.PROTECT, to='timesheet.timesheettype', verbose_name='TYPE'),
        ),
    ]
