# Generated by Django 5.0.1 on 2024-02-01 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 0, 59, 15, 451703), editable=False, verbose_name='DATE ADDED'),
        ),
    ]
