# Generated by Django 5.0.1 on 2024-02-01 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_alter_timesheetentry_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimesheetEntry',
            new_name='Entry',
        ),
        migrations.RenameModel(
            old_name='TimesheetType',
            new_name='Type',
        ),
    ]
